name: Update
on:
  push:
    branches:
      - master
jobs:
  Update-Data:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: PreInstall
        run: mv package.json __package.json

      - name: Install Deps
        run: yarn add typescript ts-node @types/node @saber2pr/node @saber2pr/git @saber2pr/ts-compiler @typescript/twoslash

      - name: PostInstall
        run: rm package.json && mv __package.json package.json

      - name: Login
        run: git config --global user.email "saber2pr@gmail.com" && git config --global user.name "saber2pr"

      # - name: Compiling Types
      #   run: yarn job

      - name: Push Data
        run: yarn push:blog

      # - name: Update CDN
      #   run: curl https://purge.jsdelivr.net/gh/saber2pr/saber2pr.github.io@master/static/data/typesdef.json
