name: Update
on:
  push:
    branches:
      - master
jobs:
  Update-Data:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn install

      - name: Push Data
        run: yarn push:blog
