name: Update
on:
  push:
    branches:
      - master
jobs:
  Update-PR:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install Deps
        run: yarn install
        
      - name: Push
        run: yarn update
        
      - name: Create Draft
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'patch-update-data'
