name: PPT
on:
  workflow_dispatch:
    inputs:
      markdown:
        description: 'markdown path'
        required: true
        
jobs:
  PPT-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: rm package.json && npm i -g markppt
       
      - name: Create PPT
        run: markppt .${{github.event.inputs.markdown}}.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog
